### ISSUE TITLE
Update-GitModule with Gitlab

### ISSUE THREAD

**Issue by OneManMonkeySquad** [iricigor/InstallModuleFromGit#47]
Module was successfully installed with 
`Install-GitModule https://git/XX/hotdog`
and its commands are working. When trying to update via
`Update-GitModule https://git/XX/hotdog`
I get the error
> PackageManagement\Get-Package : No match was found for the specified search criteria and module names 'hotdog'.
> In C:\Users\XX\Documents\WindowsPowerShell\Modules\PowerShellGet\2.2.1\PSModule.psm1:9421 Zeichen:9
> PackageManagement\Get-Package @PSBoundParameters | Microsoft. ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
> FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage

Looking through PackageManagement\Get-Package @PSBoundParameters does not include my module (why would it ^^). Am I doing something wrong?

The module is internal tooling and not available to the public. https://git is a locally running Gitlab server.

**Comment by God-damnit-all** [comment]
This error comes from `Get-InstalledModule` which is called in `Update-GitModule.ps1`, it is actually a harmless error because it's building an array composed of results from both `Get-InstalledModule` and `Get-Module`. It only means that the package isn't available through PowerShellGet.

@iricigor To fix this, add -ErrorAction SilentlyContinue to line 54 of `Update-GitModule.ps1` like so:
```powershell
            $AllModules = @((Get-Module -Name $ModuleName -ListAvailable),(Get-InstalledModule -Name $ModuleName -ErrorAction SilentlyContinue)) | Select Name, Version

**Comment by iricigor** [comment]
Hell @OneManMonkeySquad, I added error action as suggested by @ImportTaste. Please check if version 1.2 is works as you would expect and close the issue if so.

**Comment by OneManMonkeySquad** [comment]
Using nuget now instead but I'm sure this would have fixed the issue. Thank you :)
